export const REQUEST_BANNER = 'REQUEST_BANNER'
export const REQUEST_BANNER_SUCCESS = 'REQUEST_BANNER_SUCCESS'
export const REQUEST_BANNER_FAILED = 'REQUSET_BANNER_FAILED'

export const REQUEST_LOCATION = 'REQUEST_LOCATION'
export const REQUEST_LOCATION_SUCCESS = 'REQUEST_LOCATION_SUCCESS'
export const REQUEST_LOCATION_FAILED = 'REQUEST_LOCATION_FAILED'

export const REQUEST_SHOWTIME = 'REQUEST_SHOWTIME'
export const REQUSET_SHOWTIME_FAILED = 'REQUEST_SHOWTIME_FAILED'
export const REQUEST_SHOwTIME_SUCCESS = 'REQUEST_SHOWTIME_SUCCESS'