export const REQUEST_BANNER = 'REQUEST_BANNER'
export const REQUEST_BANNER_SUCCESS = 'REQUEST_BANNER_SUCCESS'
export const REQUEST_BANNER_FAILED = 'REQUSET_BANNER_FAILED'

export const REQUEST_LOCATION = 'REQUEST_LOCATION'
export const REQUEST_LOCATION_SUCCESS = 'REQUEST_LOCATION_SUCCESS'
export const REQUEST_LOCATION_FAILED = 'REQUEST_LOCATION_FAILED'

export const REQUEST_SHOWTIME = 'REQUEST_SHOWTIME'
export const REQUSET_SHOWTIME_FAILED = 'REQUEST_SHOWTIME_FAILED'
export const REQUEST_SHOwTIME_SUCCESS = 'REQUEST_SHOWTIME_SUCCESS'

export const REQUEST_FEATURE_MOVIES = 'REQUEST_FEATURE_MOVIES'
export const REQUEST_FEATURE_MOVIES_SUCCESS = 'REQUEST_FEATURE_MOVIES_SUCCESS'
export const REQUEST_FEATURE_MOVIES_FAILED = 'REQUEST_FEATURE_MOVIES_FAILED'

export const REQUEST_EVENT_LIST = 'REQUEST_EVENT_LIST'
export const REQUEST_EVENT_LIST_SUCCESS = 'REQUEST_EVENT_LIST_SUCCESS'
export const REQUEST_EVENT_LIST_FAILED = 'REQUEST_EVENT_LIST_FAILED'